/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.home.redditap;

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author GreatMahdi
 */
public class Login_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Login_Panel
     */
    public Login_Panel() {
        initComponents();
    }
    public static String LoggedInUsername;
    public static JFrame Profile_Frame;
    public static JFrame SignUP_Frame;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RedditMiniLogo = new javax.swing.JLabel();
        UserNameFeild = new javax.swing.JTextField();
        ShowPassBox = new javax.swing.JCheckBox();
        ShowPassword = new javax.swing.JLabel();
        DontHaveAccount = new javax.swing.JLabel();
        SignupButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        PassFeild = new javax.swing.JPasswordField();
        PassWord = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        Gradient = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(450, 450));
        setMinimumSize(new java.awt.Dimension(450, 450));
        setName(""); // NOI18N
        setLayout(null);

        RedditMiniLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\GreatMahdi\\Desktop\\RedditCloneAP1403-Develop\\RedditCloneAP1403-Develop\\Pictures\\RedditICO2.png")); // NOI18N
        add(RedditMiniLogo);
        RedditMiniLogo.setBounds(240, 30, 70, 60);

        UserNameFeild.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UserNameFeild.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserNameFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameFeildActionPerformed(evt);
            }
        });
        add(UserNameFeild);
        UserNameFeild.setBounds(230, 140, 200, 40);

        ShowPassBox.setBackground(new java.awt.Color(9, 69, 73));
        ShowPassBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPassBoxActionPerformed(evt);
            }
        });
        add(ShowPassBox);
        ShowPassBox.setBounds(410, 260, 20, 30);

        ShowPassword.setBackground(new java.awt.Color(255, 255, 255));
        ShowPassword.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        ShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        ShowPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShowPassword.setText("Show Password");
        add(ShowPassword);
        ShowPassword.setBounds(320, 250, 90, 50);

        DontHaveAccount.setBackground(new java.awt.Color(255, 255, 255));
        DontHaveAccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DontHaveAccount.setForeground(new java.awt.Color(255, 255, 255));
        DontHaveAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DontHaveAccount.setText("Don,t Have An Account ?");
        add(DontHaveAccount);
        DontHaveAccount.setBounds(80, 400, 260, 40);

        SignupButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        SignupButton.setText("Signup");
        SignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButtonActionPerformed(evt);
            }
        });
        add(SignupButton);
        SignupButton.setBounds(350, 400, 110, 40);

        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        add(LoginButton);
        LoginButton.setBounds(210, 310, 110, 40);

        PassFeild.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PassFeild.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PassFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassFeildActionPerformed(evt);
            }
        });
        add(PassFeild);
        PassFeild.setBounds(230, 210, 200, 40);

        PassWord.setBackground(new java.awt.Color(255, 255, 255));
        PassWord.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PassWord.setForeground(new java.awt.Color(255, 255, 255));
        PassWord.setText("Password  :");
        add(PassWord);
        PassWord.setBounds(110, 210, 120, 40);

        UserName.setBackground(new java.awt.Color(255, 255, 255));
        UserName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UserName.setForeground(new java.awt.Color(255, 255, 255));
        UserName.setText("Username :");
        add(UserName);
        UserName.setBounds(110, 140, 120, 40);

        Gradient.setIcon(new javax.swing.ImageIcon("C:\\Users\\GreatMahdi\\Desktop\\RedditCloneAP1403-Develop\\RedditCloneAP1403-Develop\\Pictures\\Gradient.png")); // NOI18N
        add(Gradient);
        Gradient.setBounds(-10, -10, 570, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void PassFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassFeildActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        if (UserNameFeild.getText().trim().isEmpty() || PassFeild.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please Fill All Feilds !");
        }
        else
        {
            try 
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection Connection1 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/redditproject","root","");
                String SQLQuery1 = "SELECT * FROM users_information WHERE user_name = ? AND user_password = ?";
                PreparedStatement PreparedStatement1 = (PreparedStatement) Connection1.prepareStatement(SQLQuery1);
                PreparedStatement1.setString(1, UserNameFeild.getText());
                PreparedStatement1.setString(2, PassFeild.getText());
                ResultSet ResultSet1 = PreparedStatement1.executeQuery();
                        
                if  (ResultSet1.next())
                {
                    LoggedInUsername = UserNameFeild.getText();
                    Profile_Frame = RedditAP.Create_JFrame (new Profile_Panel(), ("Reddit - " + LoggedInUsername + " Profile") , 700,700,1);
                    Profile_Frame.setVisible(true);
                    RedditAP.Login_Frame.setVisible(false);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Username Or Password Isn,t Correct !");
                }
                Connection1.close();
                          }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void SignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupButtonActionPerformed
        SignUP_Frame = RedditAP.Create_JFrame(new Signup_Panel(),"Reddit - Signup",550,550,1);
        SignUP_Frame.setVisible(true);
        RedditAP.Login_Frame.setVisible(false);
        
    }//GEN-LAST:event_SignupButtonActionPerformed

    private void ShowPassBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassBoxActionPerformed
        if (ShowPassBox.isSelected())
        {
            PassFeild.setEchoChar('\0');
        }
        else
        {
            PassFeild.setEchoChar('\u25CF');
        }
    }//GEN-LAST:event_ShowPassBoxActionPerformed

    private void UserNameFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameFeildActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DontHaveAccount;
    private javax.swing.JLabel Gradient;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PassFeild;
    private javax.swing.JLabel PassWord;
    private javax.swing.JLabel RedditMiniLogo;
    private javax.swing.JCheckBox ShowPassBox;
    private javax.swing.JLabel ShowPassword;
    private javax.swing.JButton SignupButton;
    private javax.swing.JLabel UserName;
    private javax.swing.JTextField UserNameFeild;
    // End of variables declaration//GEN-END:variables
}
