/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.home.redditap;

import static com.home.redditap.YourPosts_Panel.YourPostTable;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GreatMahdi
 */
public class Profile_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Profile_Panel
     */
    public static JFrame MessagesFrame;
    public static JFrame FollowListFrame;
    public static JFrame SearchFrame;
    public static JFrame YourPostsFrame;
        public static JFrame ShowPostDetails_JFrame;
        
       
       public Profile_Panel() {
    initComponents();
    WelcomeDear.setText("Welcome Dear " + " " + Login_Panel.LoggedInUsername);

    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection Connection1 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/redditproject", "root", "");
        String SQLQuery1 = "SELECT caption, user_name, share_date FROM posts_information";
        PreparedStatement PreparedStatement1 = (PreparedStatement) Connection1.prepareStatement(SQLQuery1);
        ResultSet ResultSet1 = PreparedStatement1.executeQuery();
 
        DefaultTableModel tableModel = (DefaultTableModel) ProfileTable.getModel();
        while (tableModel.getRowCount() > 0) {
            tableModel.removeRow(0);
        }

        while (ResultSet1.next()) {
            tableModel.addRow(new Object[]{ResultSet1.getString("caption"), ResultSet1.getString("user_name"), ResultSet1.getString("share_date")});
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        YourPosts = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        Messages = new javax.swing.JButton();
        Followings = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProfileTable = new javax.swing.JTable();
        WelcomeDear = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Gradient = new javax.swing.JLabel();

        setLayout(null);

        YourPosts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        YourPosts.setText("Your Posts");
        YourPosts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YourPostsActionPerformed(evt);
            }
        });
        add(YourPosts);
        YourPosts.setBounds(390, 590, 110, 50);

        SearchButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        add(SearchButton);
        SearchButton.setBounds(250, 590, 110, 50);

        Messages.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Messages.setText("Messages");
        Messages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessagesActionPerformed(evt);
            }
        });
        add(Messages);
        Messages.setBounds(530, 590, 110, 50);

        Followings.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Followings.setText("Followings - Followers");
        Followings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FollowingsActionPerformed(evt);
            }
        });
        add(Followings);
        Followings.setBounds(50, 590, 170, 50);

        ProfileTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Post Caption", "User", "Sharing Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProfileTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProfileTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(120, 140, 452, 402);

        WelcomeDear.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        WelcomeDear.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeDear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(WelcomeDear);
        WelcomeDear.setBounds(40, 12, 270, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\GreatMahdi\\Desktop\\RedditCloneAP1403-Develop\\RedditCloneAP1403-Develop\\Pictures\\RedditICO2.png")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(320, 10, 60, 80);

        Gradient.setIcon(new javax.swing.ImageIcon("C:\\Users\\GreatMahdi\\Desktop\\RedditCloneAP1403-Develop\\RedditCloneAP1403-Develop\\Pictures\\Gradient.png")); // NOI18N
        add(Gradient);
        Gradient.setBounds(-9, -9, 720, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void MessagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessagesActionPerformed
        MessagesFrame = RedditAP.Create_JFrame(new Messages_Panel(),"Reddit - "+ Login_Panel.LoggedInUsername+ " Messages List",700,700,1);
        Login_Panel.Profile_Frame.setVisible(false);
        Profile_Panel.MessagesFrame.setVisible(true);                                         
    }//GEN-LAST:event_MessagesActionPerformed

    private void FollowingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FollowingsActionPerformed
        FollowListFrame = RedditAP.Create_JFrame(new FollowList_Panel(),"Reddit - "+ Login_Panel.LoggedInUsername+ " Following And Followers List",700,700,1);
        Login_Panel.Profile_Frame.setVisible(false);
        Profile_Panel.FollowListFrame.setVisible(true);
    }//GEN-LAST:event_FollowingsActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
          SearchFrame = RedditAP.Create_JFrame(new Search_Panel(),"Reddit - Search",700,700,1);
        Login_Panel.Profile_Frame.setVisible(false);
        Profile_Panel.SearchFrame.setVisible(true);  
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void YourPostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YourPostsActionPerformed
        YourPostsFrame = RedditAP.Create_JFrame(new YourPosts_Panel(),"Reddit - YourPosts",700,700,1);
        Login_Panel.Profile_Frame.setVisible(false);
        Profile_Panel.YourPostsFrame.setVisible(true); 
    }//GEN-LAST:event_YourPostsActionPerformed

    private void ProfileTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileTableMouseClicked
    DefaultTableModel model = (DefaultTableModel)ProfileTable.getModel();
        int SelectedRow = ProfileTable.getSelectedRow();
        String post = model.getValueAt(SelectedRow, 0).toString();
        String date = model.getValueAt(SelectedRow, 1).toString();
        ShowPostDetails_JFrame = RedditAP.Create_JFrame(new ShowPostDetails_Panel(Login_Panel.LoggedInUsername,post,date),"Reddit - Post Details",700,700,1);
        Login_Panel.Profile_Frame.setVisible(false);
        Profile_Panel.ShowPostDetails_JFrame.setVisible(true);   
    }//GEN-LAST:event_ProfileTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Followings;
    private javax.swing.JLabel Gradient;
    public static javax.swing.JButton Messages;
    private javax.swing.JTable ProfileTable;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel WelcomeDear;
    public static javax.swing.JButton YourPosts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
