/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.home.redditap;

/**
 *
 * @author GreatMahdi
 */
public class Search_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Search_Panel
     */
    public Search_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Search = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        SearchButton1 = new javax.swing.JButton();
        BackToProfileButton = new javax.swing.JButton();
        MiniLogo = new javax.swing.JLabel();
        Gradient = new javax.swing.JLabel();

        setLayout(null);

        Search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Search.setForeground(new java.awt.Color(255, 255, 255));
        Search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Search.setText("Search Everything You Want");
        add(Search);
        Search.setBounds(50, 110, 590, 110);

        jScrollPane1.setViewportView(jTextPane1);

        add(jScrollPane1);
        jScrollPane1.setBounds(120, 250, 450, 90);

        SearchButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SearchButton1.setForeground(new java.awt.Color(0, 0, 0));
        SearchButton1.setText("Search");
        SearchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButton1ActionPerformed(evt);
            }
        });
        add(SearchButton1);
        SearchButton1.setBounds(250, 430, 180, 40);

        BackToProfileButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackToProfileButton.setForeground(new java.awt.Color(0, 0, 0));
        BackToProfileButton.setText("Back To Profile");
        BackToProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToProfileButtonActionPerformed(evt);
            }
        });
        add(BackToProfileButton);
        BackToProfileButton.setBounds(250, 570, 180, 40);

        MiniLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\GreatMahdi\\Desktop\\RedditCloneAP1403-Develop\\RedditCloneAP1403-Develop\\Pictures\\RedditICO2.png")); // NOI18N
        MiniLogo.setText("jLabel1");
        add(MiniLogo);
        MiniLogo.setBounds(320, 10, 60, 80);

        Gradient.setIcon(new javax.swing.ImageIcon("C:\\Users\\GreatMahdi\\Desktop\\RedditCloneAP1403-Develop\\RedditCloneAP1403-Develop\\Pictures\\Gradient.png")); // NOI18N
        add(Gradient);
        Gradient.setBounds(-15, -11, 730, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void BackToProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToProfileButtonActionPerformed
        Login_Panel.Profile_Frame.setVisible(true);
    }//GEN-LAST:event_BackToProfileButtonActionPerformed

    private void SearchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BackToProfileButton;
    private javax.swing.JLabel Gradient;
    private javax.swing.JLabel MiniLogo;
    private javax.swing.JLabel Search;
    public static javax.swing.JButton SearchButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
