
package com.home.redditap;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class Signup_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Signup_Panel
     */
    public Signup_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SignUpButton = new javax.swing.JButton();
        ShowPass = new javax.swing.JLabel();
        ShowPassCheckBox = new javax.swing.JCheckBox();
        AgreeCheckBox = new javax.swing.JCheckBox();
        NameTextFeild = new javax.swing.JTextField();
        LastNameTextFeild = new javax.swing.JTextField();
        UserNameTextFeild = new javax.swing.JTextField();
        MailTextFeild = new javax.swing.JTextField();
        PasswordFeild = new javax.swing.JPasswordField();
        IAgree = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        RedditMiniLogo = new javax.swing.JLabel();
        Gradient = new javax.swing.JLabel();

        setLayout(null);

        SignUpButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(0, 0, 0));
        SignUpButton.setText("Signup");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        add(SignUpButton);
        SignUpButton.setBounds(210, 450, 110, 40);

        ShowPass.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        ShowPass.setForeground(new java.awt.Color(255, 255, 255));
        ShowPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ShowPass.setText("Show Password ?");
        add(ShowPass);
        ShowPass.setBounds(390, 340, 140, 60);

        ShowPassCheckBox.setBackground(new java.awt.Color(9, 69, 73));
        ShowPassCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPassCheckBoxActionPerformed(evt);
            }
        });
        add(ShowPassCheckBox);
        ShowPassCheckBox.setBounds(501, 350, 19, 40);

        AgreeCheckBox.setBackground(new java.awt.Color(9, 69, 73));
        AgreeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgreeCheckBoxActionPerformed(evt);
            }
        });
        add(AgreeCheckBox);
        AgreeCheckBox.setBounds(420, 400, 20, 40);

        NameTextFeild.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NameTextFeild.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NameTextFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFeildActionPerformed(evt);
            }
        });
        add(NameTextFeild);
        NameTextFeild.setBounds(180, 110, 220, 40);

        LastNameTextFeild.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LastNameTextFeild.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LastNameTextFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextFeildActionPerformed(evt);
            }
        });
        add(LastNameTextFeild);
        LastNameTextFeild.setBounds(180, 170, 220, 40);

        UserNameTextFeild.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UserNameTextFeild.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserNameTextFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTextFeildActionPerformed(evt);
            }
        });
        add(UserNameTextFeild);
        UserNameTextFeild.setBounds(180, 290, 220, 40);

        MailTextFeild.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MailTextFeild.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MailTextFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailTextFeildActionPerformed(evt);
            }
        });
        add(MailTextFeild);
        MailTextFeild.setBounds(180, 230, 220, 40);

        PasswordFeild.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PasswordFeild.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(PasswordFeild);
        PasswordFeild.setBounds(180, 350, 220, 40);

        IAgree.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        IAgree.setForeground(new java.awt.Color(255, 255, 255));
        IAgree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IAgree.setText("I Agree All Of The Terms And Conditions");
        add(IAgree);
        IAgree.setBounds(40, 390, 420, 60);

        Password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Password.setText("Password :");
        add(Password);
        Password.setBounds(50, 350, 130, 40);

        UserName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UserName.setForeground(new java.awt.Color(255, 255, 255));
        UserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserName.setText("Email :");
        add(UserName);
        UserName.setBounds(50, 230, 130, 40);

        Email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Email.setText("Username :");
        add(Email);
        Email.setBounds(50, 290, 130, 40);

        LastName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LastName.setForeground(new java.awt.Color(255, 255, 255));
        LastName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LastName.setText("Lastname :");
        add(LastName);
        LastName.setBounds(50, 170, 130, 40);

        Name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("Name :");
        add(Name);
        Name.setBounds(50, 110, 130, 40);

        RedditMiniLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\GreatMahdi\\Desktop\\RedditCloneAP1403-Develop\\RedditCloneAP1403-Develop\\Pictures\\RedditICO2.png")); // NOI18N
        add(RedditMiniLogo);
        RedditMiniLogo.setBounds(240, 30, 70, 60);

        Gradient.setIcon(new javax.swing.ImageIcon("C:\\Users\\GreatMahdi\\Desktop\\RedditCloneAP1403-Develop\\RedditCloneAP1403-Develop\\Pictures\\Gradient.png")); // NOI18N
        Gradient.setText("jLabel1");
        add(Gradient);
        Gradient.setBounds(-13, -10, 580, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void NameTextFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFeildActionPerformed

    private void LastNameTextFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextFeildActionPerformed

    private void UserNameTextFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTextFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTextFeildActionPerformed

    private void MailTextFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailTextFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MailTextFeildActionPerformed

    private void AgreeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgreeCheckBoxActionPerformed
    }//GEN-LAST:event_AgreeCheckBoxActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        if (NameTextFeild.getText().trim().isEmpty() || LastNameTextFeild.getText().trim().isEmpty() || MailTextFeild.getText().trim().isEmpty() || PasswordFeild.getText().trim().isEmpty() || UserNameTextFeild.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please Fill All Feilds !");
        }
        else
        {
            try
            {
              Class.forName("com.mysql.jdbc.Driver");
                Connection Connection1 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/redditproject","root","");
                String SQLQuery1 = "SELECT * FROM users_information WHERE user_name = ? AND user_email = ?";
                PreparedStatement PreparedStatement1 = (PreparedStatement) Connection1.prepareStatement(SQLQuery1);
                PreparedStatement1.setString(1, UserNameTextFeild.getText());
                PreparedStatement1.setString(2, MailTextFeild.getText());
                          ResultSet ResultSet1 = PreparedStatement1.executeQuery();   
                          int i = 0;
                          if (ResultSet1.next())
                          {
                              i++;
                          }
                          
                          
                          if (i == 0)
                          {
                              String SQLQuery2 = "INSERT INTO users_information (firstname,lastname,user_name,user_password,user_email) VALUES (?,?,?,?,?)";
                              PreparedStatement PreparedStatement2 = (PreparedStatement) Connection1.prepareStatement(SQLQuery2);
                              PreparedStatement2.setString(1, NameTextFeild.getText());
                              PreparedStatement2.setString(2, LastNameTextFeild.getText());
                              PreparedStatement2.setString(3, UserNameTextFeild.getText());
                              PreparedStatement2.setString(4, PasswordFeild.getText());
                              PreparedStatement2.setString(5, MailTextFeild.getText());
                              PreparedStatement2.executeUpdate();
                              JOptionPane.showMessageDialog(null, "Welcome To Reddit Dear " + UserNameTextFeild.getText());                            
                              Login_Panel.SignUP_Frame.setVisible(false);
                                RedditAP.Login_Frame.setVisible(true);
                          }
                          else
                          {
                              JOptionPane.showMessageDialog(null, "Username Or Email Are Already Used ! Try Again !");
                                                            RedditAP.Login_Frame.setVisible(false);
                              Login_Panel.SignUP_Frame.setVisible(true);
                                     }
}
                          
                          catch (Exception e)
                                  {
                                  JOptionPane.showMessageDialog(null,e);
                                  }
            }
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void ShowPassCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassCheckBoxActionPerformed
               if (ShowPassCheckBox.isSelected())
        {
            PasswordFeild.setEchoChar('\0');
        }
        else
        {
            PasswordFeild.setEchoChar('\u25CF');
        }
    }//GEN-LAST:event_ShowPassCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AgreeCheckBox;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Gradient;
    private javax.swing.JLabel IAgree;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LastNameTextFeild;
    private javax.swing.JTextField MailTextFeild;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameTextFeild;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordFeild;
    private javax.swing.JLabel RedditMiniLogo;
    private javax.swing.JLabel ShowPass;
    private javax.swing.JCheckBox ShowPassCheckBox;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JLabel UserName;
    private javax.swing.JTextField UserNameTextFeild;
    // End of variables declaration//GEN-END:variables
}
